FROM openjdk:8-jre

RUN mkdir /opt/refidp
ADD target/dependency/apache-tomcat-8.5.9 /opt/refidp/tomcat/
ADD target/shibboleth /opt/refidp/shibboleth/

# Redirecting log directories
RUN rm -rf /opt/refidp/tomcat/logs && ln -s /var/log/refidp/ /opt/refidp/tomcat/logs
RUN rm -rf /opt/refidp/shibboleth/logs && ln -s /var/log/refidp/ /opt/refidp/shibboleth/logs
RUN chmod a+x /opt/refidp/tomcat/bin/*.sh
EXPOSE 8443

VOLUME /etc/refidp
VOLUME /var/log/refidp
CMD mkdir -p /var/log/refidp/ && /opt/refidp/tomcat/bin/dockerDevStart.sh refidp
