#
# Configuration for the Swedish eIDAS Connector.
#

server:
  port: 8443
  servlet:
    context-path: /idp
    session:
      cookie:
        name: EIDASSESSION
        domain: ${connector.domain}
        max-age: 60m
        same-site: NONE
        http-only: true
        secure: true
  ssl:
    enabled: true
    key-store: classpath:ssl.jks
    key-store-type: JKS
    key-alias: local
    key-store-password: secret
    key-password: secret
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    
#
# Management/Actuator configuration
#
management:
  server:
    port: 8444
  endpoint:
    health:
      status:
        order:
        - DOWN
        - OUT_OF_SERVICE
        - UP
        - WARNING
        - UNKNOWN
        http-mapping:
          WARNING: 503
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, refresh-prid, logfile, auditevents 

spring:
  messages:    
    basename: messages,idp-errors/idp-error-messages
        
ui:
  languages:
  - tag: sv
    text: Svenska
  - tag: en
    text: English
  selected-country-cookie:
    path: ${server.servlet.context-path}
    domain: ${connector.domain}
  selected-country-session-cookie:
    path: ${server.servlet.context-path}
    domain: ${connector.domain}
  accessibility-url: https://www.swedenconnect.se/om/om-webbplatsen/tillganglighet/svenska-eidas-noden       

connector:
  backup-directory: target
  base-url: https://${connector.domain}:${server.port}/${server.servlet.context-path}
  country: SE  
  idp:
    entity-categories:
    - http://id.elegnamnden.se/ec/1.0/eidas-naturalperson
    - http://id.elegnamnden.se/sprop/1.0/scal2
    - http://id.elegnamnden.se/sprop/1.0/mobile-auth
  eu-metadata:
    backup-location: ${connector.backup-directory}/metadata/eu-cache.xml
  eidas:
    entity-id: ${saml.idp.base-url}/metadata/sp
    requires-signed-assertions: true
    preferred-binding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
    skip-scoping-for:
    - DK
    metadata:
      application-identifier-prefix: "SE:connector:"
      protocol-versions:
      - 1.0
      - 1.1
      - 1.2
      organization:
        names: 
          en: Sweden Connect
        display-names:
          en: "Swedish eIDAS node"
        urls:
          en: https://www.swedenconnect.se/en
      contact-persons:
        technical:
          company: "Sweden Connect"
          given-name: "Technical support"
          email-addresses:
          - operations@swedenconnect.se
        support:
          company: "Sweden Connect"
          given-name: "Customer support"
          email-addresses:
          - operations@swedenconnect.se
      digest-methods:
      - http://www.w3.org/2001/04/xmlenc#sha256
      - http://www.w3.org/2001/04/xmldsig-more#sha384
      - http://www.w3.org/2001/04/xmlenc#sha512
      include-digest-methods-under-role: true
      signing-methods:
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1
        min-key-size: 3072
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha384-rsa-MGF1
        min-key-size: 3072
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha512-rsa-MGF1
        min-key-size: 3072
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
        min-key-size: 256
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
        min-key-size: 256
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
        min-key-size: 256
      include-signing-methods-under-role: true
      encryption-methods:
      - algorithm: http://www.w3.org/2009/xmlenc11#aes256-gcm
      - algorithm: http://www.w3.org/2009/xmlenc11#aes192-gcm
      - algorithm: http://www.w3.org/2009/xmlenc11#aes128-gcm
      - algorithm: http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
      - algorithm: http://www.w3.org/2009/xmlenc11#rsa-oaep
      
saml:
  idp:
    entity-id: https://connector.eidas.swedenconnect.se/eidas
    base-url: ${connector.base-url}    
    credentials:
      sign:
        resource: classpath:idp-credentials.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: classpath:idp-credentials.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:idp-credentials.jks
        alias: metadata
        password: secret
        type: JKS
    endpoints:
      metadata: /metadata/idp.xml
      post-authn: /profile/SAML2/POST/SSO
      redirect-authn: /profile/SAML2/Redirect/SSO
    requires-signed-requests: true  
    metadata:
      digest-methods:
      - http://www.w3.org/2001/04/xmlenc#sha256
      - http://www.w3.org/2001/04/xmldsig-more#sha384
      - http://www.w3.org/2001/04/xmlenc#sha512
      include-digest-methods-under-role: true
      signing-methods:
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
        min-key-size: 2048
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
        min-key-size: 2048
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
        min-key-size: 2048      
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1
        min-key-size: 2048
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha384-rsa-MGF1
        min-key-size: 2048
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha512-rsa-MGF1
        min-key-size: 2048
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
        min-key-size: 256
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
        min-key-size: 256
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
        min-key-size: 256
      include-signing-methods-under-role: true
      encryption-methods:
      - algorithm: http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
      - algorithm: http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
        digest-method: http://www.w3.org/2001/04/xmlenc#sha256
      - algorithm: http://www.w3.org/2009/xmlenc11#aes256-gcm
      - algorithm: http://www.w3.org/2009/xmlenc11#aes192-gcm
      - algorithm: http://www.w3.org/2009/xmlenc11#aes128-gcm
      - algorithm: http://www.w3.org/2001/04/xmlenc#aes256-cbc
      - algorithm: http://www.w3.org/2001/04/xmlenc#aes192-cbc
      - algorithm: http://www.w3.org/2001/04/xmlenc#aes128-cbc
      requested-principal-selection:
      # prid
      - "urn:oid:1.2.752.201.3.4"
      # eidasPersonIdentifier
      - "urn:oid:1.2.752.201.3.7"
      # personalIdentityNumber
      - "urn:oid:1.2.752.29.4.13"
      # mappedPersonalIdentityNumber
      - "urn:oid:1.2.752.201.3.16"
      # c
      - "urn:oid:2.5.4.6"
      ui-info:
        display-names:
          en: "Foreign eID"
          sv: "Utländskt eID"
        descriptions:
          en: "Identity Provider for foreign eID:s"
          sv: "Legitimeringstjänst för utländsk legitimering"
        logotypes:
        - path: /images/idp-logo-notext.svg
          height: 256
          width: 256
        - path: /images/idp-logo.svg
          height: 56
          width: 280      
      organization:
        names:
          en: Sweden Connect
          sv: Sweden Connect
        display-names:
          en: Sweden Connect
          sv: Sweden Connect
        urls:
          en: https://www.swedenconnect.se/en
          sv: https://www.swedenconnect.se
      contact-persons:
        technical:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se
        support:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se

logging:
  level:
    se:
      swedenconnect:
        eidas: DEBUG

---

spring:
  config:
    activate:
      on-profile: production
      
connector:
  domain: connector.eidas.swedenconnect.se
  eu-metadata:
    location: https://md.eidas.swedenconnect.se/role/idp.xml
    validation-certificate: classpath:env/production/eu-metadata-signing-prod.crt
    
saml:
  idp:
    entity-id: https://connector.eidas.swedenconnect.se/eidas
    base-url: https://connector.eidas.swedenconnect.se/idp
    metadata-providers:
    - location: https://md.swedenconnect.se/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:env/production/sc-metadata-signing-prod.crt

logging:
  level:
    se:
      swedenconnect:
        eidas: INFO      

---

spring:
  config:
    activate:
      on-profile: qa

connector:
  domain: qa.connector.eidas.swedenconnect.se
  eu-metadata:
    location: https://qa.md.eidas.swedenconnect.se/role/idp.xml
    validation-certificate: classpath:env/qa/eu-metadata-signing-qa.crt
  idp:
    ping-whitelist:
    - https://qa.test.swedenconnect.se/sp

saml:
  idp:
    entity-id: https://qa.connector.eidas.swedenconnect.se/eidas
    base-url: https://qa.connector.eidas.swedenconnect.se/idp  
    metadata-providers:
    - location: https://qa.md.swedenconnect.se/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:env/qa/sc-metadata-signing-qa.crt

logging:
  level:
    se:
      swedenconnect:
        eidas: INFO

---

spring:
  config:
    activate:
      on-profile: sandbox
      
connector:
  domain: con.sandbox.swedenconnect.se
  eu-metadata:
    location: https://mdsl.sandbox.swedenconnect.se/nodeconfig/metadata
    validation-certificate: classpath:env/sandbox/eu-metadata-signing-sandbox.crt
  idp:
    ping-whitelist:
    - http://sandbox.swedenconnect.se/testmyeid

saml:
  idp:
    entity-id: https://dev.connector.swedenconnect.se/eidas
    base-url: https://con.sandbox.swedenconnect.se/idp  
    metadata-providers:
    - location: https://eid.svelegtest.se/metadata/mdx/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:env/sandbox/sc-metadata-signing-sandbox.crt
    credentials:
      sign:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: old-signing
        password: secret
        type: JKS
      encrypt:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: metadata
        password: secret
        type: JKS
      future-sign: classpath:env/sandbox/idp-signing.crt
      previous-encrypt:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: old-encrypt
        password: secret
        type: JKS
        

logging:
  level:
    se:
      swedenconnect:
        eidas: INFO

---

spring:
  config:
    activate:
      on-profile: localhost
      
server:
  port: 9200      
      
connector:
  domain: localhost
  base-url: https://${connector.domain}:${server.port}/${server.servlet.context-path}
  eu-metadata:
    location: file:${LOCAL_ENV_PATH}/eidas/eu-metadata/metadata.xml
    #validation-certificate: classpath:env/qa/eu-metadata-signing-qa.crt  
#  eu-metadata:
#    location: https://mdsl.sandbox.swedenconnect.se/nodeconfig/metadata
#    validation-certificate: classpath:env/sandbox/eu-metadata-signing-sandbox.crt
  idp:
    ping-whitelist:
    - http://sandbox.swedenconnect.se/testmyeid
  eidas:
    entity-id: https://localhost:9200/idp/metadata/sp    
    credentials:
      sign:
        resource: classpath:env/localhost/sp-keys.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: classpath:env/localhost/sp-keys.jks
        alias: encrypt
        password: secret
        type: JKS
  
saml:
  idp:
    entity-id: https://eunode.eidastest.se/idp2
    metadata-providers:
    - location: https://eid.svelegtest.se/metadata/mdx/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:env/sandbox/sc-metadata-signing-sandbox.crt
    credentials:
      sign:
        resource: classpath:env/localhost/idp-keys.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: classpath:env/localhost/idp-keys.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:env/localhost/idp-keys.jks
        alias: metadata
        password: secret
        type: JKS        
    metadata:
      ui-info:
        display-names:
          en: Local Sweden Connect Reference IdP
          sv: Local Sweden Connect Referens-IdP
        descriptions:
          en: Local Sweden Connect Reference Identity Provider
          sv: Local Sweden Connect referens-legitimeringstjänst
        logotypes:
        - path: /images/logo-notext.svg
          height: 256
          width: 256
        - path: /images/logo.svg
          height: 56
          width: 280
          
logging:
  level:
    se:
      swedenconnect: DEBUG
    org:
      opensaml:
        core:
          config: DEBUG      
      
