#
# Connector overrides for the QA deployment
#
spring:
  ssl:
    bundle:
      pem:
        connector-web-server:
          keystore:
            certificate: file:${CONNECTOR_DIRECTORY}/credentials/server.crt
            private-key: file:${CONNECTOR_DIRECTORY}/credentials/server.key
        sunet-tls-trust:
          truststore:
            certificate: file:${CONNECTOR_DIRECTORY}/credentials/trusted-certs.crt

server:
  port: 8443
  servlet:
    context-path: /idp
  ssl:
    enabled: true
    bundle: connector-web-server
  error:
    include-stacktrace: never

management:
  server:
    port: 8444
  health:
    redis:
      enabled: true

credential:
  bundles:
    pem:
      connector:
        # TODO: Fix certs
        name: "Connector Credential"
        certificates: file:${CONNECTOR_DIRECTORY}/credentials/connector.crt
        private-key: file:${CONNECTOR_DIRECTORY}/credentials/connector.key
      oauth2:
        # TODO: Fix certs
        name: "Connector OAuth2 Credential"
        certificates: file:${CONNECTOR_DIRECTORY}/credentials/oauth2.crt
        private-key: file:${CONNECTOR_DIRECTORY}/credentials/oauth2.key

connector:
  domain: qa.connector.eidas.swedenconnect.se
  base-url: https://${connector.domain}${server.servlet.context-path}
  backup-directory: ${CONNECTOR_DIRECTORY}/backup
  eu-metadata:
    location: https://qa.md.eidas.swedenconnect.se/role/idp.xml
    validation-certificate: file:${CONNECTOR_DIRECTORY}/metadata/eu-metadata-signing-qa.crt
  eidas:
    credentials:
      sign:
        bundle: connector
      encrypt:
        bundle: connector
  prid:
    policy-resource: file:${CONNECTOR_DIRECTORY}/prid/prid-policy.yml
  idp:
    ping-whitelist:
      - https://qa.test.swedenconnect.se/sp
  idm:
    # TODO: Change to true when IdM integration should be turned on
    active: false
    api-base-url: https://qa.idm.eidas.swedenconnect.se/idm
    service-url: https://qa.idm.eidas.swedenconnect.se/idm
    oauth2:
      resource-id: https://qa.idm.eidas.swedenconnect.se/idm
      client-id: ${saml.idp.entity-id}
      check-scopes:
        - ${connector.idm.oauth2.resource-id}/idrecord_check
      get-scopes:
        - ${connector.idm.oauth2.resource-id}/idrecord_get
      server:
        issuer: ${saml.idp.entity-id}/as
      credential:
        bundle: oauth2

saml:
  idp:
    entity-id: https://qa.connector.eidas.swedenconnect.se/eidas
    base-url: ${connector.base-url}
    metadata-providers:
      - location: https://qa.md.swedenconnect.se/role/sp.xml
        backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
        validation-certificate: file:${CONNECTOR_DIRECTORY}/metadata/sc-metadata-signing-qa.crt
    credentials:
      sign:
        bundle: connector
      encrypt:
        bundle: connector
      metadata-sign:
        bundle: connector
      #future-sign: file:${CONNECTOR_DIRECTORY}/credentials/idp-signing.crt
    audit:
      in-memory:
        capacity: 1000
      file:
        log-file: ${CONNECTOR_DIRECTORY}/logs/audit.log

logging:
  level:
    se:
      swedenconnect:
        eidas: INFO
