#
# Configuration for the Swedish eIDAS Connector.
#

server:
  port: 8443
  servlet:
    context-path: /idp    
  ssl:
    enabled: true
    key-store: classpath:ssl.jks
    key-store-type: JKS
    key-alias: local
    key-store-password: secret
    key-password: secret
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always

spring:
  messages:
    basename: messages,idp-errors/idp-error-messages
    
ui:
  languages:
  - tag: sv
    text: Svenska
  - tag: en
    text: English
  selected-country-cookie:
    path: ${server.servlet.context-path}
  selected-country-session-cookie:
    path: ${server.servlet.context-path}
  accessibility-url: https://www.swedenconnect.se/om/om-webbplatsen/tillganglighet/svenska-eidas-noden
  idm:
    active: true
    # TODO: change
    service-url: https://sandbox.swedenconnect.se/idm
       

connector:
  backup-directory: /target  
  idp:
    entity-categories:
    - http://id.elegnamnden.se/ec/1.0/eidas-naturalperson
    - http://id.elegnamnden.se/sprop/1.0/scal2
    - http://id.elegnamnden.se/sprop/1.0/mobile-auth
  eu-metadata:
    backup-location: ${connector.backup-directory}/metadata/eu-cache.xml

saml:
  idp:
    entity-id: https://connector.eidas.swedenconnect.se/eidas
    base-url: https://connector.eidas.swedenconnect.se/idp    
    credentials:
      sign:
        resource: classpath:idp-credentials.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: classpath:idp-credentials.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:idp-credentials.jks
        alias: metadata
        password: secret
        type: JKS
    endpoints:
      metadata: /metadata/idp.xml
      post-authn: /profile/SAML2/POST/SSO
      redirect-authn: /profile/SAML2/Redirect/SSO
    requires-signed-requests: true  
    metadata-providers:
    - location: https://eid.svelegtest.se/metadata/mdx/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:sandbox-metadata.crt
    metadata:
      ui-info:
        display-names:
          en: "Foreign eID"
          sv: "Utländskt eID"
        descriptions:
          en: "Identity Provider for foreign eID:s"
          sv: "Legitimeringstjänst för utländsk legitimering"
        logotypes:
        - path: /images/idp-logo-notext.svg
          height: 256
          width: 256
        - path: /images/idp-logo.svg
          height: 56
          width: 280   
      organization:
        names:
          en: Sweden Connect
          sv: Sweden Connect
        display-names:
          en: Sweden Connect
          sv: Sweden Connect
        urls:
          en: https://www.swedenconnect.se/en
          sv: https://www.swedenconnect.se
      contact-persons:
        technical:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se
        support:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se        

logging:
  level:
    se:
      swedenconnect:
        eidas: DEBUG

---

spring:
  config:
    activate:
      on-profile: production
      
connector:
  eu-metadata:
    location: https://md.eidas.swedenconnect.se/role/idp.xml
    validation-certificate: classpath:env/production/eu-metadata-signing-prod.crt
    
saml:
  idp:
    entity-id: https://connector.eidas.swedenconnect.se/eidas
    base-url: https://connector.eidas.swedenconnect.se/idp
    metadata-providers:
    - location: https://md.swedenconnect.se/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:env/production/sc-metadata-signing-prod.crt

logging:
  level:
    se:
      swedenconnect:
        eidas: INFO      

---

spring:
  config:
    activate:
      on-profile: qa

connector:
  eu-metadata:
    location: https://qa.md.eidas.swedenconnect.se/role/idp.xml
    validation-certificate: classpath:env/qa/eu-metadata-signing-qa.crt

saml:
  idp:
    entity-id: https://qa.connector.eidas.swedenconnect.se/eidas
    base-url: https://qa.connector.eidas.swedenconnect.se/idp  
    metadata-providers:
    - location: https://qa.md.swedenconnect.se/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:env/qa/sc-metadata-signing-qa.crt

logging:
  level:
    se:
      swedenconnect:
        eidas: INFO

---

spring:
  config:
    activate:
      on-profile: sandbox
      
connector:
  eu-metadata:
    location: https://mdsl.sandbox.swedenconnect.se/nodeconfig/metadata
    validation-certificate: classpath:env/sandbox/eu-metadata-signing-sandbox.crt

saml:
  idp:
    entity-id: https://dev.connector.swedenconnect.se/eidas
    base-url: https://con.sandbox.swedenconnect.se/idp  
    metadata-providers:
    - location: https://eid.svelegtest.se/metadata/mdx/role/sp.xml
      backup-location: ${connector.backup-directory}/metadata/sc-cache.xml
      validation-certificate: classpath:env/sandbox/sc-metadata-signing-sandbox.crt
    credentials:
      sign:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: old-signing
        password: secret
        type: JKS
      encrypt:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: metadata
        password: secret
        type: JKS
      future-sign: classpath:env/sandbox/idp-signing.crt
      previous-encrypt:
        resource: classpath:env/sandbox/idp-keys.jks
        alias: old-encrypt
        password: secret
        type: JKS
        

logging:
  level:
    se:
      swedenconnect:
        eidas: INFO

---

spring:
  config:
    activate:
      on-profile: localhost
  
saml:
  idp:
    entity-id: https://local.swedenconnect.se/idp
    metadata:
      ui-info:
        display-names:
          en: Local Sweden Connect Reference IdP
          sv: Local Sweden Connect Referens-IdP
        descriptions:
          en: Local Sweden Connect Reference Identity Provider
          sv: Local Sweden Connect referens-legitimeringstjänst
        logotypes:
        - path: /images/logo-notext.svg
          height: 256
          width: 256
        - path: /images/logo.svg
          height: 56
          width: 280
      
